update release.yaml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -18,6 +18,52 @@ jobs:
         with:
           fetch-depth: 0
 
+      - name: Validate Tag Format
+        run: |
+          TAG=${GITHUB_REF#refs/tags/}
+          
+          SV_REGEX="^(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-((0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9][0-9]*|[0-9]*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$"
+
+          if ! [[ $TAG =~ $SV_REGEX ]]; then
+            echo "$TAG is NOT a valid semver string"
+            exit 1
+          fi
+
+      - name: Check Version Consistency
+        run: |
+          # Extract tag and remove 'v' prefix if exists
+          TAG=${GITHUB_REF#refs/tags/}
+          TAG_CLEAN=$(echo $TAG | sed 's/^v//')
+          
+          # Read version from connector.yaml
+          YAML_VERSION=$(yq e '.specification.version' connector.yaml)
+          YAML_VERSION_CLEAN=$(echo $YAML_VERSION | sed 's/^v//')
+          
+          # Compare versions
+          if [[ "$TAG_CLEAN" != "$YAML_VERSION_CLEAN" ]]; then
+            echo "Version mismatch detected:"
+            echo "Git Tag: $TAG"
+            echo "connector.yaml Version: $YAML_VERSION"
+            exit 1
+          fi
+
+      - name: Delete Invalid Tag
+        if: failure()
+        uses: actions/github-script@v7
+        with:
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            const tag = context.ref.replace('refs/tags/', '')
+            try {
+              await github.rest.git.deleteRef({
+                owner: context.repo.owner,
+                repo: context.repo.repo,
+                ref: `tags/${tag}`
+              })
+            } catch (error) {
+              console.log('Error deleting tag:', error)
+            }
+
       - name: Set up Go
         uses: actions/setup-go@v5
         with:
